for number in range(99, 1, -1):
	print """{0} bottles of beer on the wall, {0} bottle of beer ...
			If one of those bottles should happen to fall, {1} bottles of beer on the wall""".format(number, number-1)
